# Generated by Django 6.0.3 on 2026-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CPU', 'Procesador'), ('MB', 'Placa Base'), ('RAM', 'Memoria RAM'), ('CASE', 'Caja/Torre'), ('COOL', 'Refrigeración'), ('GPU', 'Tarjeta Gráfica'), ('PSU', 'Fuente Alimentación'), ('SSD', 'Almacenamiento'), ('MON', 'Monitor'), ('NONE', 'Otro')], default='NONE', max_length=4),
        ),
    ]
