# Generated by Django 6.0.3 on 2026-03-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CPU', 'Procesador'), ('MB', 'Placa Base'), ('RAM', 'Memoria RAM'), ('CASE', 'Caja/Torre'), ('COOL', 'Refrigeración'), ('GPU', 'Tarjeta Gráfica'), ('PSU', 'Fuente Alimentación'), ('SSD', 'Almacenamiento'), ('MON', 'Monitor'), ('NONE', 'Otro'), ('VG_TEND', 'VG - Tendencia'), ('VG_RES', 'VG - Reserva'), ('VG_REC', 'VG - Recomendación')], default='NONE', max_length=7),
        ),
    ]
