# Generated by Django 6.0.3 on 2026-04-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_imagen_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CPU', 'Procesador'), ('MB', 'Placa Base'), ('RAM', 'Memoria RAM'), ('CASE', 'Caja/Torre'), ('AIR', 'Refrigeración Aire'), ('LIQ', 'Refrigeración Líquida'), ('GPU', 'Tarjeta Gráfica'), ('PSU', 'Fuente Alimentación'), ('SSD', 'Almacenamiento'), ('MON', 'Monitor'), ('NONE', 'Otro'), ('VG_TEND', 'VG - Tendencia'), ('VG_RES', 'VG - Reserva'), ('VG_REC', 'VG - Recomendación')], default='NONE', max_length=7),
        ),
    ]
