# Generated by Django 6.0.3 on 2026-04-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
