# Generated by Django 6.0.4 on 2026-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alertaprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=500)),
                ('nombre_candidato_db', models.CharField(max_length=500)),
                ('es_mismo_producto', models.BooleanField()),
                ('fecha_decision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre_tienda', 'nombre_candidato_db'], name='api_decisio_nombre__79db39_idx')],
                'unique_together': {('nombre_tienda', 'nombre_candidato_db')},
            },
        ),
    ]
