# Generated by Django 6.0.4 on 2026-04-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_decisionia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CPU', 'Procesador'), ('MB', 'Placa Base'), ('RAM', 'Memoria RAM'), ('CASE', 'Caja/Torre'), ('AIR', 'Refrigeración Aire'), ('LIQ', 'Refrigeración Líquida'), ('GPU', 'Tarjeta Gráfica'), ('PSU', 'Fuente Alimentación'), ('SSD', 'Almacenamiento'), ('MON', 'Monitor'), ('NONE', 'Otro'), ('VG_TEND', 'VG - Tendencia'), ('VG_RES', 'VG - Reserva'), ('VG_REC', 'VG - Recomendación')], db_index=True, default='NONE', max_length=7),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
