# Generated by Django 6.0.4 on 2026-05-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_producto_categoria_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tienda_logos/'),
        ),
    ]
